<?php

define('ABSPATH','/media/CENAS/vhosts/historiasdagomeira/');

$wp_load_location = ABSPATH .'/wp-load.php';

echo $wp_load_location;

if (file_exists($wp_load_location)) {
	require_once   $wp_load_location;
} else {
	die();
}

require_once dirname(__DIR__) . '/gtm_plugin_main.php';

class TestGeocodedMedia extends PHPUnit_Framework_TestCase {


	private function deactivatePlugins($plugins_off) {
		echo "=>Unloading plugins ...\n";
		print_r($plugins_off);


		deactivate_plugins($plugins_off);
		$active_plugins = get_option('active_plugins');
	//	$plugins = array_diff($active_plugins,$plugins_off);
		print_r($active_plugins);
		return $active_plugins;
	}
	protected function setUp() {

		$this->deactivatePlugins(array(
			'wp-php-console/wp-php-console.php'
		));

		//parent::setUp(); // TODO: Change the autogenerated stub


	}


	public function testgtm_is_metadata_empty() {
		$r = $wp_get_attachment_metadata = array();
		$resp = $this->testgtm_is_metadata_empty($r);
		$this->assertTrue($resp);
	}

}
